version: "2"

services:
    data:
        image: vertisfinance/baseimage
        hostname: data
        command: start
        volumes:
            - /var/lib/data
        entrypoint: ["python3", "entry.py"]
        command: start
        stop_signal: SIGINT

    postgres:
        image: vertisfinance/postgres
        hostname: postgres-example
        volumes_from:
            - data
        volumes:
            - ./pg_hba.conf:/pg_hba.conf
            - ./postgresql.conf:/postgresql.conf
        entrypoint: ["python3", "entry.py"]
        environment:
            USER_NAME: postgres
            USER_ID: 5432
            PGDATA: /var/lib/data/pgdata
            SOCKET_DIR: /var/lib/data/sock
            BACKUP_DIR: /var/lib/data/backup
            SEMAPHORE: /var/lib/data/semaphore/postgres.semaphore
            MAIN_USER_PWD: unsafe!change
            DB_PASSWORD_trac: trac
            DB_OWNER_TRAC: trac
        command: start
        ports:
            - "5432:5432"

    trac:
        image: vertisfinance/trac
        hostname: trac
        entrypoint: ["python3", "entry.py"]
        command: start
